import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { AppMetadataProvider } from "@/context/AppMetadataContext";
export const metadata: Metadata = {
  title: "Secure Shell",
  description: "Generated by Eddy Seed",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AppMetadataProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
        </AppMetadataProvider>
      </body>
    </html>
  );
}
